#!/bin/sh

function main {
    case "$1" in
        "certs") certs;;
        "stop") stop;;
        "matchbox") matchbox;;
        "create-nodes") createNodes;;
    esac
}

function certs {
    terraform apply
}

function stop {
    systemctl stop matchbox matchbox-dnsmasq
    rkt gc --grace-period=0s
    systemctl reset-failed
}

function matchbox {
    systemd-run --unit=matchbox -p WorkingDirectory=$(pwd) \
      rkt run \
      --insecure-options=image,ondisk \
      --stage1-path=/usr/lib/rkt/stage1-images/stage1-coreos.aci \
      --net=metal0:IP=10.1.1.2 \
      --dns=10.1.1.3 \
      quay.io/coreos/matchbox:latest \
      --mount volume=assets,target=/var/lib/matchbox/assets \
      --volume assets,kind=host,source=$PWD/assets \
      --mount volume=etc-matchbox,target=/etc/matchbox \
      --volume etc-matchbox,kind=host,source=$PWD/matchbox \
      -- \
      -address=0.0.0.0:8080 \
      -rpc-address=0.0.0.0:8081 \
      -log-level=debug

    systemd-run --unit=matchbox-dnsmasq -p WorkingDirectory=$(pwd) \
      rkt run \
      --insecure-options=image,ondisk \
      --stage1-path=/usr/lib/rkt/stage1-images/stage1-coreos.aci \
      --net=metal0:IP=10.1.1.3 \
      --dns=10.1.1.3 \
      quay.io/coreos/dnsmasq \
      --caps-retain=CAP_NET_ADMIN,CAP_NET_BIND_SERVICE \
      --mount volume=config,target=/etc/dnsmasq.conf \
      --volume config,kind=host,source=$PWD/dnsmasq/metal0.conf \
      --mount volume=resolv,target=/etc/resolv.dnsmasq \
      --volume resolv,kind=host,source=$PWD/dnsmasq/resolv.dnsmasq \
      --mount volume=hosts,target=/etc/hosts.dnsmasq \
      --volume hosts,kind=host,source=$PWD/dnsmasq/hosts.dnsmasq
}

COMMON_VIRT_OPTS="--memory=4096 --vcpus=1 --pxe --disk pool=default,size=6 --os-type=linux --os-variant=generic --noautoconsole"

function createNodes {
    virt-install --name master1 --network=bridge:metal0,mac=0a:0b:0c:0d:0e:10 $COMMON_VIRT_OPTS --boot=hd,network
    virt-install --name worker1 --network=bridge:metal0,mac=0a:0b:0c:0d:0e:11 $COMMON_VIRT_OPTS --boot=hd,network
}

main $@
